
Bpi\ApiBundle\Domain\Aggregate\Agency:
  collection: Agency
  repositoryClass: Bpi\ApiBundle\Domain\Repository\AgencyRepository

  fields:
    id:
      id: true
    public_id:
      type: string
      unique: true
      order: true
    name:
      type: string
    moderator:
      type: string
    internal:
      type: boolean
    secret:
      type: string
    public_key:
      type: string
      unique:
        order: desc
    deleted:
        type: boolean
