bpi_admin_homepage:
    pattern:  /
    defaults: { _controller: BpiAdminBundle:Default:index }

bpi_admin_agency:
    pattern: /agency
    defaults: { _controller: BpiAdminBundle:Agency:index }

bpi_admin_agency_details:
    pattern: /agency/details/{id}
    defaults: { _controller: BpiAdminBundle:Agency:details }

bpi_admin_agency_new:
    pattern: /agency/new
    defaults: { _controller: BpiAdminBundle:Agency:new }

bpi_admin_agency_edit:
    pattern: /agency/edit/{id}
    defaults: { _controller: BpiAdminBundle:Agency:edit }

bpi_admin_agency_delete:
    pattern: /agency/delete/{id}
    defaults: { _controller: BpiAdminBundle:Agency:delete }

bpi_admin_agency_purge:
    pattern: /agency/purge/{id}
    defaults: { _controller: BpiAdminBundle:Agency:purge }

bpi_admin_agency_restore:
    pattern: /agency/restore/{id}
    defaults: { _controller: BpiAdminBundle:Agency:restore }

bpi_admin_agency_deleted:
    pattern: /agency/deleted
    defaults: { _controller: BpiAdminBundle:Agency:deleted }

bpi_admin_node:
    pattern:  /node
    defaults: { _controller: BpiAdminBundle:Node:index }

bpi_admin_node_details:
    pattern: /node/details/{id}
    defaults: { _controller: BpiAdminBundle:Node:details }

bpi_admin_node_new:
    pattern: /node/new
    defaults: { _controller: BpiAdminBundle:Node:new }

bpi_admin_node_edit:
    pattern: /node/edit/{id}
    defaults: { _controller: BpiAdminBundle:Node:edit }

bpi_admin_node_delete:
    pattern: /node/delete/{id}
    defaults: { _controller: BpiAdminBundle:Node:delete }

bpi_admin_node_restore:
    pattern: /node/restore/{id}
    defaults: { _controller: BpiAdminBundle:Node:restore }

bpi_admin_node_deleted:
    pattern: /node/deleted
    defaults: { _controller: BpiAdminBundle:Node:deleted }

bpi_admin_statistics:
    pattern: /statistics
    defaults: { _controller: BpiAdminBundle:Statistics:index }

bpi_admin_category:
    pattern:  /category
    defaults: { _controller: BpiAdminBundle:Category:index }

bpi_admin_category_new:
    pattern: /category/new
    defaults: { _controller: BpiAdminBundle:Category:new }

bpi_admin_category_edit:
    pattern: /category/edit/{id}
    defaults: { _controller: BpiAdminBundle:Category:edit }

bpi_admin_audience:
    pattern:  /audience
    defaults: { _controller: BpiAdminBundle:Audience:index }

bpi_admin_audience_new:
    pattern: /audience/new
    defaults: { _controller: BpiAdminBundle:Audience:new }

bpi_admin_audience_edit:
    pattern: /audience/edit/{id}
    defaults: { _controller: BpiAdminBundle:Audience:edit }
